const data = {
  base: [
    { hira: "あ", kata: "ア", roman: "a" },
    { hira: "い", kata: "イ", roman: "i" },
    { hira: "う", kata: "ウ", roman: "u" },
    { hira: "え", kata: "エ", roman: "e" },
    { hira: "お", kata: "オ", roman: "o" },
    { hira: "か", kata: "カ", roman: "ka" },
    { hira: "き", kata: "キ", roman: "ki" },
    { hira: "く", kata: "ク", roman: "ku" },
    { hira: "け", kata: "ケ", roman: "ke" },
    { hira: "こ", kata: "コ", roman: "ko" },
    { hira: "さ", kata: "サ", roman: "sa" },
    { hira: "し", kata: "シ", roman: "shi" },
    { hira: "す", kata: "ス", roman: "su" },
    { hira: "せ", kata: "セ", roman: "se" },
    { hira: "そ", kata: "ソ", roman: "so" },
    { hira: "た", kata: "タ", roman: "ta" },
    { hira: "ち", kata: "チ", roman: "chi" },
    { hira: "つ", kata: "ツ", roman: "tsu" },
    { hira: "て", kata: "テ", roman: "te" },
    { hira: "と", kata: "ト", roman: "to" },
    { hira: "な", kata: "ナ", roman: "na" },
    { hira: "に", kata: "ニ", roman: "ni" },
    { hira: "ぬ", kata: "ヌ", roman: "nu" },
    { hira: "ね", kata: "ネ", roman: "ne" },
    { hira: "の", kata: "ノ", roman: "no" },
    { hira: "は", kata: "ハ", roman: "ha" },
    { hira: "ひ", kata: "ヒ", roman: "hi" },
    { hira: "ふ", kata: "フ", roman: "hu" },
    { hira: "へ", kata: "ヘ", roman: "he" },
    { hira: "ほ", kata: "ホ", roman: "ho" },
    { hira: "ま", kata: "マ", roman: "ma" },
    { hira: "み", kata: "ミ", roman: "mi" },
    { hira: "む", kata: "ム", roman: "mu" },
    { hira: "め", kata: "メ", roman: "me" },
    { hira: "も", kata: "モ", roman: "mo" },
    { hira: "や", kata: "ヤ", roman: "ya" },
    { hira: "い", kata: "イ", roman: "i" },
    { hira: "ゆ", kata: "ユ", roman: "yu" },
    { hira: "え", kata: "エ", roman: "e" },
    { hira: "よ", kata: "ヨ", roman: "yo" },
    { hira: "ら", kata: "ラ", roman: "ra" },
    { hira: "り", kata: "リ", roman: "ri" },
    { hira: "る", kata: "ル", roman: "ru" },
    { hira: "れ", kata: "レ", roman: "re" },
    { hira: "ろ", kata: "ロ", roman: "ro" },
    { hira: "わ", kata: "ワ", roman: "wa" },
    { hira: "い", kata: "イ", roman: "i" },
    { hira: "う", kata: "ウ", roman: "u" },
    { hira: "え", kata: "エ", roman: "e" },
    { hira: "を", kata: "ヲ", roman: "wo" },
  ],
  vibrant1: [
    { hira: "が", kata: "ガ", roman: "ga" },
    { hira: "ぎ", kata: "ギ", roman: "gi" },
    { hira: "ぐ", kata: "グ", roman: "gu" },
    { hira: "げ", kata: "ゲ", roman: "ge" },
    { hira: "ご", kata: "ゴ", roman: "go" },
    { hira: "ざ", kata: "ザ", roman: "za" },
    { hira: "じ", kata: "ジ", roman: "ji" },
    { hira: "ず", kata: "ズ", roman: "zu" },
    { hira: "ぜ", kata: "ゼ", roman: "ze" },
    { hira: "ぞ", kata: "ゾ", roman: "zo" },
    { hira: "だ", kata: "ダ", roman: "da" },
    { hira: "ぢ", kata: "ヂ", roman: "ji" },
    { hira: "づ", kata: "ヅ", roman: "zu" },
    { hira: "で", kata: "デ", roman: "de" },
    { hira: "ど", kata: "ド", roman: "do" },
    { hira: "ば", kata: "バ", roman: "ba" },
    { hira: "び", kata: "ビ", roman: "bi" },
    { hira: "ぶ", kata: "ブ", roman: "bu" },
    { hira: "べ", kata: "ベ", roman: "be" },
    { hira: "ぼ", kata: "ボ", roman: "bo" },
  ],
  vibrant2: [
    { hira: "ぱ", kata: "パ", roman: "pa" },
    { hira: "ぴ", kata: "ピ", roman: "pi" },
    { hira: "ぷ", kata: "プ", roman: "pu" },
    { hira: "ぺ", kata: "ぺ", roman: "pe" },
    { hira: "ぽ", kata: "ポ", roman: "po" },
  ],
};
